markdown: kramdown
permalink: /:title/
url: https://phenge.github.io
name: PMLTIPS
author: PMLTIPS
qq: 
email: pmltips@163.com
beian: 
cnzz: 
weibo: 
resp: phenge.github.io
github: phenge
safe: true
paginate: 20
about: "这里是 PMLTIPS 的个人博客，欢迎观赏、建议、拍砖……"
