markdown: kramdown
permalink: /:title/
url: https://phenge.github.io
name: Phenge
author: Phenge
qq: 45580817
email: sfzhi@163.com
beian: 
cnzz: 119959
weibo: 1885061391
github: phenge
safe: true
paginate: 20
about: "这里是 Phenge 的个人博客，欢迎观赏、建议、拍砖……"
